"""init

Revision ID: 187781a6ad3e
Revises: 
Create Date: 2025-02-19 01:39:06.834401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187781a6ad3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imageData', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passwordHash', sa.Text(), nullable=True),
    sa.Column('EmailAdress', sa.String(length=50), nullable=True),
    sa.Column('UserName', sa.String(length=50), nullable=True),
    sa.Column('Private', sa.Boolean(), nullable=True),
    sa.Column('ProfilePictureId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProfilePictureId'], ['profile_pictures.id'], name=op.f('fk_users_ProfilePictureId_profile_pictures')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('EmailAdress')
    )
    op.create_table('following',
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('FollowedUserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FollowedUserId'], ['users.id'], name=op.f('fk_following_FollowedUserId_users')),
    sa.ForeignKeyConstraint(['UserId'], ['users.id'], name=op.f('fk_following_UserId_users'))
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=50), nullable=True),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('ParentPostId', sa.Integer(), nullable=True),
    sa.Column('RepostId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ParentPostId'], ['posts.id'], name=op.f('fk_posts_ParentPostId_posts')),
    sa.ForeignKeyConstraint(['RepostId'], ['posts.id'], name=op.f('fk_posts_RepostId_posts')),
    sa.ForeignKeyConstraint(['UserId'], ['users.id'], name=op.f('fk_posts_UserId_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('DarkMode', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.id'], name=op.f('fk_settings_UserId_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('PostId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['PostId'], ['posts.id'], name=op.f('fk_likes_PostId_posts')),
    sa.ForeignKeyConstraint(['UserId'], ['users.id'], name=op.f('fk_likes_UserId_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('settings')
    op.drop_table('posts')
    op.drop_table('following')
    op.drop_table('users')
    op.drop_table('profile_pictures')
    # ### end Alembic commands ###
