"""added language to user settings

Revision ID: 19d45e6ed475
Revises: 501a41cd39e6
Create Date: 2025-02-28 00:15:39.026165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d45e6ed475'
down_revision = '501a41cd39e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('Language')

    # ### end Alembic commands ###
