"""add creation_date to post

Revision ID: 501a41cd39e6
Revises: 187781a6ad3e
Create Date: 2025-02-19 18:48:20.875471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501a41cd39e6'
down_revision = '187781a6ad3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
