"""Fix settings model relationships

Revision ID: d84ce87cab0c
Revises: 19d45e6ed475
Create Date: 2025-03-12 12:52:48.858073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84ce87cab0c'
down_revision = '19d45e6ed475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('DarkMode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('Language',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('Language',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('DarkMode',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
